### ISSUE TITLE
howto listen udp

### ISSUE THREAD

**Issue by teamuppolska** [Cinegy/TsAnalyser#4]
Hi guys - is it possible to receive udp multicasts?

**Comment by lewk2** [comment]
Yep - there is now a '-n' option which skips reading RTP headers, expecting instead just plain TS mode.

**Comment by teamuppolska** [comment]
Thanks Lewis!!!

LUKASZ BRODOWSKI
mailto: lukasz@teamup.pl
mobile: +48 600 156 666

www.teamup.pl

**Comment by lewk2** [comment]
Fixed a couple of other bugs where multiple NICs would make it not work, and tuned the logging performance too.

Enjoy!
